### ISSUE TITLE
Reward treatment

### ISSUE THREAD

**Issue by jviquerat** [chagmgang/tf2.0_reinforcement_learning#1]
Hi,

Thanks for the very clear implementations !
Would you mind elaborating on the following lines ? It seems like you are making the reward sparse on purpose, and I don't think I have seen similar treatment in other PPO implementations : 

https://github.com/chagmgang/tf2.0_reinforcement_learning/blob/32df21c7436027e3d81bfbc9ad5a8137a94c3685/policy/ppo.py#L148-L154

Again, thanks for sharing your work ;)

**Comment by chagmgang** [comment]
Thanks for interest in my implementation.
Then, you want to convert reward sparse to reward dense environment?

**Comment by jviquerat** [comment]
I was just wondering why you were voluntarily putting reward to 0 except for the final value. Did you find some interest in doing that ? Is it based on a PPO variant/paper ?
Thanks in advance ;)

**Comment by chagmgang** [comment]
The reason why I use sparse environment in cartpole-v1 is proving that the advantage calculation is correctly implemented. I verified that my PPO code is well done in both sparse environment and dense environment.

**Comment by jviquerat** [comment]
Oh, okay I understand :)
Thank you for the answer !
